-- Baseline schema, captured from the Hibernate-managed dev schema (ddl-auto=update)
-- via jakarta.persistence.schema-generation.scripts.action=create.

create table app_users (
    user_id bigint generated by default as identity,
    user_type varchar(31) not null,
    name varchar(255) not null,
    username varchar(255) not null unique,
    password varchar(255) not null,
    email varchar(255) not null unique,
    phone varchar(10) not null unique,
    created_at timestamp(6) not null,
    primary key (user_id)
);

create table app_admins (
    user_id bigint not null,
    admin_level integer,
    primary key (user_id),
    constraint fk_admins_user foreign key (user_id) references app_users
);

create table app_pharmacists (
    user_id bigint not null,
    employee_id bigint,
    license_number varchar(255),
    primary key (user_id),
    constraint fk_pharmacists_user foreign key (user_id) references app_users
);

create table app_customers (
    user_id bigint not null,
    customer_id bigint,
    address varchar(255),
    loyalty_points integer not null,
    primary key (user_id),
    constraint fk_customers_user foreign key (user_id) references app_users
);

create table app_suppliers (
    user_id bigint not null,
    supplier_id bigint,
    company_name varchar(255),
    contact_info varchar(255),
    primary key (user_id),
    constraint fk_suppliers_user foreign key (user_id) references app_users
);

create table app_medicines (
    medicine_id bigint generated by default as identity,
    medicine_type varchar(31) not null,
    name varchar(255) not null unique,
    category varchar(255) not null,
    manufacturer varchar(255),
    price numeric(12,2) not null,
    stock_qty integer not null,
    expiry_date date not null,
    low_stock_threshold integer not null,
    updated_at timestamp(6) not null,
    version bigint,
    primary key (medicine_id)
);

create table app_orders (
    order_id bigint generated by default as identity,
    customer_id bigint not null,
    ordered_at timestamp(6) not null,
    total_amount numeric(12,2) not null,
    status enum ('CREATED','BILLED','PAID','DECLINED','CANCELLED') not null,
    primary key (order_id),
    constraint fk_orders_customer foreign key (customer_id) references app_customers
);

create table app_order_items (
    order_item_id bigint generated by default as identity,
    order_id bigint not null,
    medicine_id bigint not null,
    quantity integer not null,
    unit_price numeric(12,2) not null,
    line_total numeric(12,2) not null,
    primary key (order_item_id),
    constraint fk_order_items_order foreign key (order_id) references app_orders,
    constraint fk_order_items_medicine foreign key (medicine_id) references app_medicines
);

create table app_bills (
    bill_id bigint generated by default as identity,
    order_id bigint not null unique,
    subtotal numeric(12,2) not null,
    discount_amount numeric(12,2) not null,
    tax_amount numeric(12,2) not null,
    total numeric(12,2) not null,
    generated_at timestamp(6) not null,
    primary key (bill_id),
    constraint fk_bills_order foreign key (order_id) references app_orders
);

create table app_payments (
    payment_id bigint generated by default as identity,
    bill_id bigint not null unique,
    amount numeric(12,2) not null,
    payment_method enum ('CASH','CARD','UPI') not null,
    status enum ('SUCCESS','FAILED','PENDING') not null,
    paid_at timestamp(6) not null,
    primary key (payment_id),
    constraint fk_payments_bill foreign key (bill_id) references app_bills
);

create table app_prescriptions (
    prescription_id bigint generated by default as identity,
    customer_id bigint not null,
    medicine_id bigint not null,
    doctor_name varchar(255) not null,
    dosage varchar(255) not null,
    notes varchar(255),
    prescribed_at timestamp(6) not null,
    primary key (prescription_id),
    constraint fk_prescriptions_customer foreign key (customer_id) references app_customers,
    constraint fk_prescriptions_medicine foreign key (medicine_id) references app_medicines
);

create table app_procurement_invoices (
    invoice_id bigint generated by default as identity,
    supplier_id bigint not null,
    invoice_number varchar(255) not null unique,
    amount numeric(12,2) not null,
    payment_status enum ('PENDING','PROCESSED','DECLINED','CANCELLED') not null,
    submitted_at timestamp(6) not null,
    paid_at timestamp(6),
    primary key (invoice_id),
    constraint fk_invoices_supplier foreign key (supplier_id) references app_suppliers
);

create table app_procurement_invoice_items (
    invoice_item_id bigint generated by default as identity,
    invoice_id bigint not null,
    medicine_id bigint not null,
    quantity integer not null,
    unit_price numeric(12,2) not null,
    line_total numeric(12,2) not null,
    primary key (invoice_item_id),
    constraint fk_invoice_items_invoice foreign key (invoice_id) references app_procurement_invoices,
    constraint fk_invoice_items_medicine foreign key (medicine_id) references app_medicines
);

create table app_shipments (
    shipment_id bigint generated by default as identity,
    supplier_id bigint not null,
    medicine_id bigint not null,
    invoice_id bigint,
    quantity integer not null,
    status enum ('IN_TRANSIT','DELIVERED','DECLINED','CANCELLED') not null,
    expected_date date not null,
    delivered_at timestamp(6),
    primary key (shipment_id),
    constraint fk_shipments_supplier foreign key (supplier_id) references app_suppliers,
    constraint fk_shipments_medicine foreign key (medicine_id) references app_medicines,
    constraint fk_shipments_invoice foreign key (invoice_id) references app_procurement_invoices
);

create table app_reports (
    report_id bigint generated by default as identity,
    report_type enum ('SALES','INVENTORY') not null,
    generated_by varchar(255) not null,
    summary clob not null,
    data clob not null,
    generated_at timestamp(6) not null,
    primary key (report_id)
);
